[metadata]
name = astlib
version = 0.0.1

[options]
#packages = astlib
install_requires =
    matplotlib
    pyelftools
    pandas
    rich
    seaborn
    graphviz
    pyhidra
    zss
    # wildebeest @ git+ssh://git@github.com/lasserre/wildebeest.git#egg=wildebeest
    # wildebeest @ git+ssh://git@github.com/lasserre/wildebeest.git

[options.entry_points]
console_scripts =
    bcdiff = astlib.scripts.bcdiff:main
    diff_asts = astlib.scripts.diff_asts:main
    print_ast = astlib.scripts.print_ast:main
    run_validation = astlib.scripts.run_validation:main
    report_ast_export = astlib.scripts.report_ast_export:main
    ghidra_decompile_all = ghidralib.export_ast:decompile_all_main
